### ISSUE TITLE
[Database Request] Half-Life 2

### ISSUE THREAD

**Issue by Kaperios** [BlueManCZ/SIF#10] opened 2020-10-24 20:31 UTC
Also Half-Life 2: Lost Coast, Half-Life 2: Episode One and Half-Life 2: Episode Two

It seems like HL2 is already in the database but the icon doesn't match the icon I've seen in the Papirus icon theme.

**APP_ID:** 220, 340, 380, 420
**WM_CLASS:** hl2_linux
**WM_NAME:** HALF-LIFE 2 - OpenGL
**Icon Theme:** Papirus-Dark

**Comment by BlueManCZ** [comment] 2020-10-24 20:46
This is strange. I understand the DLCs are not in the database, but Half-Life 2 itself should work. It does for me. What icon do you see?

![Snímek z 2020-10-24 22-44-07](https://user-images.githubusercontent.com/17854950/97093258-a9608c80-164a-11eb-8d28-fdb1b9fdfe3b.png)

**Comment by Kaperios** [comment] 2020-10-24 20:50
This is the icon I see: 
![image](https://user-images.githubusercontent.com/17909958/97093334-48858400-164b-11eb-97a3-1bae06641b60.png)

**Comment by BlueManCZ** [comment] 2020-10-24 20:52
And when you apply the fix, you see Half-Life 2 was fixed?

**Comment by Kaperios** [comment] 2020-10-24 20:53
The script says it applies the icon, I can see some added launch parameters but the icon doesn't change

**Comment by Kaperios** [comment] 2020-10-24 20:56
Okay, found the issue and I think I know its cause. It happens to all the games that have to get additional launch parameters.
And the cause of them not working for me might be my shell which is not POSIX compliant (fish).

**Comment by BlueManCZ** [comment] 2020-10-24 20:58
Alright, this can be a problem. Can you confirm it works with any different shell?

**Comment by Kaperios** [comment] 2020-10-24 21:02
Okay so changing the shell to zsh did not fix the problem

**Comment by BlueManCZ** [comment] 2020-10-24 21:05
I kind of don't know how to debug it, but did you restart Steam after changing the shell?

**Comment by Kaperios** [comment] 2020-10-24 21:05
I had to end the session to fully change the shell so yeah I did

**Comment by BlueManCZ** [comment] 2020-10-24 21:08
Ok, what do you get when you perform `xprop WM_CLASS` on the "fixed" Half-Life 2?

**Comment by Kaperios** [comment] 2020-10-24 21:09
Huh, `HALF-LIFE 2 - OpenGL`

**Comment by BlueManCZ** [comment] 2020-10-24 21:13
So the fix does kind of work. The another thing that came to my mind is what panel or dock you use?

**Comment by Kaperios** [comment] 2020-10-24 21:20
I use Latte

**Comment by BlueManCZ** [comment] 2020-10-24 22:27
The thing is that games without specific WM_CLASS are more complicated to fix.

Right now I do it by running [fix-wm-class.sh](https://github.com/BlueManCZ/SIF/blob/master/fix-wm-class.sh) script from the game launch parameters, as you may have noticed. It changes runtime WM_CLASS of the game window. This means the icon is de-facto changed in a short time after the game is started. But it requires dock to fetch icons from icon theme dynamicaly (I guess). If Latte doesn't support dynamic icons, it will create a launcher instance with a default icon and never change it afterwards.

Problem is, I didn't find a better solution than this and I guess it doesn't even exist.

**BUT** I have to test it myself and confirm this. If I'm right, we can discuss it in [latte-dock](https://github.com/KDE/latte-dock) repository.

**Comment by BlueManCZ** [comment] 2020-10-25 11:01
Alright. I didn't even need to install Latte and I see those icons don't work even in the default KDE panel. The problem is I can't do much about it. Can you please try [Plank dock](https://github.com/ricotz/plank) and confirm it works at least here? If it does, we can create an issue in the relevant tracker and ask developers about it.

**Comment by Kaperios** [comment] 2020-10-25 14:11
It does indeed work in plank. Actually it works in Plank too well because I have a folder opened with the name "Euro Truck Simulator 2" in dolphin and it changes icon of that too

**Comment by BlueManCZ** [comment] 2020-10-25 16:21
Okay. So would you mind testing those newly added problematic games in Plank and closing issues for games that do work? I will create a new issue about what we talked here and let developers know about it.

**Comment by Kaperios** [comment] 2020-10-25 18:12
Done, thanks for putting so much work into this

**Closed** 2020-10-26 11:08 UTC
Labels: bug
